with ada.integer_text_io;
use ada.integer_text_io;

with text_io;
use text_io;

with sgf;
use sgf;

Procedure testsgf is
Begin
	Put_Line("--Création de l'arbre :");
	Format;
	Put_Line("--Test du Pwd à la racine");
	Pwd;
	Put_Line("--Test du Cd dans un fils");
	Cd("temp");
	Put_Line("--Test de Touch");
	Touch("test.jpg");
	Touch("RickRoll.jpg");
	Put_Line("--Test du Mkdir");
	Mkdir("Test");
	Put_Line("--Test du Ls");
	Ls;
	Put_Line("--Test du Pwd dans une aborescense");
	Pwd;
	Put_Line("--Test du cd ./");
	Cd("./");
	Pwd;
	Put_Line("--Test du cd ../");
	cd("../");
	Pwd;
	cd("temp");
	Put_Line("--Test du cd avec un retour racine /temp/Test");
	Cd("/temp/Test");
	Pwd;
	Put_Line("--Test du cd en racine /");
	Cd("/");
	Pwd;
	Put_Line("--Test pour se déplacer dans un fichier");
	Cd("/temp/test.jpg");
	Put_Line("--Test pour se déplacer vers un dossier qui n'existe pas");
	Cd("adjdhjd");
	Pwd;
	Put_Line("--Test du ls -r");
	LsR;
	Put_Line("--Test du RM d'un fichier");
	Cd("temp");
	Rm("test.jpg");
	Ls;
	Put_Line("--Test du RM d'un repertoire 'Test'");
	Rm("Test");
	Ls;
	Put_Line("--Test de Rm un fichier qui n'existe pas");
	Rm("gqdhfghq");
	Put_Line("--Test de Rm -r d'un repertoire");
	RmR("Test");
	Ls;
	Put_Line("--Test de Rm -r d'un fichier");
	RmR("RickRoll.jpg");
	Ls;
	Put_Line("--Test de Rm -r d'un repertoire qui n'existe pas");
	RmR("qdjhqhdjf");
	Put_Line("--Test MV un fichier existant vers un dossier existant");
	Pwd;
	Ls;
	Mv("RickRoll.jpg","/etc");
	Pwd;
	Ls;
	Cd("/etc");
	Pwd;
	Ls;
	Put_Line("--Test MV un repertoire vers un dossier existant");
	Mkdir("Test");
	Pwd;
	Ls;
	Mv("Test","/bin");
	Pwd;
	Ls;
	Put_Line("--Test Mv un fichier qui existe vers un dossier inexistant");
	Pwd;
	Ls;
	Mv("RickRoll.jpg","kdlskdls");
	Pwd;
	Ls;
	Put_Line("--Test Mv un fichier qui n'existe pas vers un dossier existant");
	Pwd;
	Ls;
	Mv("kjfkjdkfjd","/bin");
	Cd("/bin");
	Pwd;
	Ls;
	Put_Line("--Test Cpr d'un fichier existant vers un dossier existant");
	Cd("/etc");
	Pwd;
	Ls;
	Cpr("RickRoll.jpg","/bin");
	Pwd;
	Ls;
	Cd("/bin");
	Pwd;
	Ls;
	Put_Line("--Test Cpr d'un repertoire existant vers un dossier existant");
	Cd("/etc");
	Pwd;
	Ls;
	Cpr("Test","/bin");
	Pwd;
	Ls;
	Cd("/bin");
	Pwd;
	Ls;
	Put_Line("--Test Cpr d'un fichier existant vers un dossier inexistant");
	Cd("/etc");
	Pwd;
	Ls;
	Cpr("RickRoll.jpg","/jdfkjdk");
	Put_Line("--Test Cpr d'un fichier inexistant vers un dossier existant");
	Cd("/etc");
	Pwd;
	Ls;
	Cpr("ajdkj","/bin");
	Cd("/bin");
	Pwd;
	Ls;
	Put_Line("--Test Cpr d'un repertoire contenant un arborecence vers un dossier existant");
	Cd("/");
	Pwd;
	Ls;
	Cpr("bin","/etc");
	Cd("./etc");
	Pwd;
	LsR;
	Put_Line("--Test d'atteinte de capacite Max & test de fichier du même nom");
	Cd("/");
	Touch("Test");
	Touch("Test");
	Touch("Test");
	Touch("Test");
	Touch("Test");
	Touch("Test");
	Touch("Test");
	GetCapacite;
	Ls;
	Put_Line("--Test monter la taille d'un fichier jusqu'à la capacite Max");
	Nano("Test","20");
	GetCapacite;
	Put_Line("--Test Baisser la taille d'un fichier");
	Nano("Test","2");
	GetCapacite;
End testsgf;